
name: Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v0.1.0